SELECT DISTINCT ST_Intersection(r.geom, w.geom) AS geom
INTO T2019_KAR_BRIDGES
FROM T2019_KAR_RAILWAYS AS r
CROSS JOIN T2019_KAR_WATER_LINES AS w
WHERE ST_Intersects(r.geom, w.geom);

SELECT *
FROM T2019_KAR_BRIDGES
